#docker run -it -p 3306:3306 -v /Users/ifew/mysql_db:/var/lib/mysql --name mysql_db mysql_db
FROM mysql:5.5 AS mysql_db
  
WORKDIR /var/lib/mysql

ENV MYSQL_DATABASE dotnet_mysql
ENV MYSQL_ROOT_USER root
ENV MYSQL_ROOT_PASSWORD 1234
ENV MYSQL_USER ifew
ENV MYSQL_PASSWORD 1234

EXPOSE 3306
CMD ["mysqld"]
